#!/usr/bin/env python3
"""B4 sweep 1 (D-11): repoint dead-agent references to surviving equivalents.

Dead-agent -> surviving-agent mapping. None = no surviving agent equivalent
(remove the reference: drop the frontmatter list line, drop the token from an
inline list, or strip the wikilink). The four reference shapes handled in *.md:
  1. YAML frontmatter list item:  "  - <dead>"
  2. Hand-authored "**Used by agents:** [[a]], [[b]]" lines
  3. Inline prose/table tokens:  `<dead>` (backticked) and [[<dead>]] wikilinks
     OUTSIDE the auto-generated block
The auto-generated link-skills block ("<!-- auto-generated by scripts/link-skills.py -->"
... end of file) is skipped — sweep 8 regenerates it and drops dead agents.

*.yaml pass (added 260611, B4 round): repoints functional dispatch + data keys
that drive runtime behavior, not prose. Two shapes:
  Y1. scalar dispatch key:  "agent: <dead>"  (campaign-runner campaign-types,
      read into state by state_manager.py:276 -> a dead agent here = a broken
      dispatch). Value must be a REAL surviving agent.
  Y2. list item under an "agents:" block, and top-level key under
      "agent_mcp_map:" (skills/common/data/mcp-mapping-matrix.yaml). Maps to a
      surviving agent and DEDUPES within the block / on key collision.
Every YAML repoint target must be a live agent in agents/*.md — never a skill —
because these fields name a worker to dispatch, not a framework to load
(the sibling "skill:" field already carries the framework).
"""
import re, sys, pathlib

ROOT = pathlib.Path(__file__).resolve().parents[3]

# dead -> surviving (None => remove reference, no equivalent agent survives)
MAP = {
    "attraction-specialist": "researcher",
    "brainstormer": "copywriter",
    "command-helper": None,
    "continuity-specialist": None,
    "docs-manager": None,
    "email-wizard": "copywriter",
    "lead-qualifier": "persona-builder",
    "mcp-manager": None,
    "planner": None,
    "project-manager": None,
    "pseo-architect": "researcher",
    "sales-enabler": "copywriter",
    "seo-specialist": "researcher",
    "solopreneur": "brand-voice-guardian",
    "startup-founder": "brand-voice-guardian",
    "tracking-specialist": "researcher",
    "upsell-maximizer": "conversion-optimizer",
}
DEAD = sorted(MAP, key=len, reverse=True)
DEAD_ALT = "|".join(re.escape(d) for d in DEAD)

# For bare-word prose/table contexts where MAP is None (no surviving agent),
# repoint to the surviving mechanism (skill name) so the sentence still resolves.
# Unambiguous hyphenated names only; ambiguous bare words (planner) handled with guards.
PROSE_NONE = {
    "command-helper": "campaign-runner",
    "continuity-specialist": "email-sequence",
    "docs-manager": "knowledge-hygiene",
    "mcp-manager": "campaign-runner",
    "planner": "campaign-runner",
    "project-manager": "campaign-runner",
}
# bare-word tokens that NEVER appear as a common noun -> safe to replace anywhere
UNAMBIG = [d for d in DEAD if "-" in d and d not in ("project-manager",)]
UNAMBIG_ALT = "|".join(re.escape(d) for d in UNAMBIG)

# Dead -> surviving LIVE AGENT for functional YAML dispatch/data keys. Unlike MAP,
# this never resolves to None: a dispatch field must name a real worker. Where MAP
# had no surviving agent (project-management roster), the closest survivor that
# covers the same MCP/work category is used (researcher plans + pulls data).
# Survivors verified present in agents/*.md this round: copywriter, persona-builder,
# researcher, conversion-optimizer, brand-voice-guardian.
AGENT_SURVIVOR = {
    "attraction-specialist": "researcher",
    "brainstormer": "copywriter",
    "command-helper": "researcher",
    "continuity-specialist": "copywriter",   # email/survey copy; skill: carries email-sequence
    "docs-manager": "researcher",
    "email-wizard": "copywriter",
    "lead-qualifier": "persona-builder",
    "mcp-manager": "researcher",
    "planner": "researcher",                 # content-calendar / planning tasks
    "project-manager": "researcher",
    "pseo-architect": "researcher",
    "sales-enabler": "copywriter",
    "seo-specialist": "researcher",
    "solopreneur": "brand-voice-guardian",
    "startup-founder": "brand-voice-guardian",
    "tracking-specialist": "researcher",
    "upsell-maximizer": "conversion-optimizer",
}

# substrings whose presence means the line is a common-noun false positive, skip wholesale
PROTECT = [
    "Budget planner",
    "Company size (solopreneur",
    "solo-steve",
    "a solopreneur wrestling",
    "Would a solopreneur implement",
    "a solopreneur arguing",  # copywriter-learnings.md prose
    "solopreneurs/creators",
]

targets = []
for base in ("skills", "commands", "agents"):
    for p in (ROOT / base).rglob("*.md"):
        if "_archive" in p.parts:
            continue
        targets.append(p)

def survivors_for(names):
    """Map a list of dead/live agent names to deduped survivor list (drop None)."""
    out = []
    for n in names:
        if n in MAP:
            repl = MAP[n]
            if repl and repl not in out:
                out.append(repl)
        else:  # already a live agent
            if n not in out:
                out.append(n)
    return out

changelog = []

for path in targets:
    raw = path.read_text(encoding="utf-8")
    lines = raw.split("\n")
    # locate auto-generated block start (skip from there to EOF)
    autogen_idx = None
    for i, ln in enumerate(lines):
        if "auto-generated by scripts/link-skills.py" in ln:
            autogen_idx = i
            break
    out_lines = []
    changed_here = []
    for i, ln in enumerate(lines):
        if autogen_idx is not None and i >= autogen_idx:
            out_lines.append(ln)
            continue
        if any(prot in ln for prot in PROTECT):
            out_lines.append(ln)
            continue
        if not re.search(DEAD_ALT, ln):
            out_lines.append(ln)
            continue
        orig = ln

        # Shape 1: YAML frontmatter list item:  "  - <dead>"  (optionally trailing comment)
        m = re.match(r"^(\s*)-\s+(" + DEAD_ALT + r")\s*(#.*)?$", ln)
        if m:
            dead = m.group(2)
            repl = MAP[dead]
            if repl is None:
                changed_here.append(f"{i+1}: removed frontmatter agent `- {dead}`")
                continue  # drop the line entirely
            else:
                newln = f"{m.group(1)}- {repl}" + (f" {m.group(3)}" if m.group(3) else "")
                out_lines.append(newln)
                changed_here.append(f"{i+1}: `- {dead}` -> `- {repl}`")
                continue

        # Shape 2: "**Used by agents:** [[a]], [[b]]"
        if "Used by agents:" in ln:
            names = re.findall(r"\[\[([a-z0-9-]+)\]\]", ln)
            surv = survivors_for(names)
            prefix = ln[: ln.index("[[")] if "[[" in ln else ln
            if surv:
                newln = prefix + ", ".join(f"[[{s}]]" for s in surv)
            else:
                # nothing survives -> drop the whole bullet
                changed_here.append(f"{i+1}: removed dead 'Used by agents' bullet ({', '.join(names)})")
                continue
            if newln != orig:
                out_lines.append(newln)
                changed_here.append(f"{i+1}: Used-by-agents {names} -> {surv}")
            else:
                out_lines.append(orig)
            continue

        # Shape 3: inline backticked token  `<dead>`  and wikilink [[<dead>]]
        new = ln
        for dead in DEAD:
            repl = MAP[dead]
            for pat in (r"`" + re.escape(dead) + r"`", r"\[\[" + re.escape(dead) + r"\]\]"):
                if re.search(pat, new):
                    if repl is None:
                        # leave a neutralized token rather than mangle table structure
                        new = re.sub(pat, ("`(retired)`" if pat.startswith("`") else "(retired)"), new)
                    else:
                        token = f"`{repl}`" if pat.startswith("`") else f"[[{repl}]]"
                        new = re.sub(pat, token, new)
        if new != orig:
            out_lines.append(new)
            changed_here.append(f"{i+1}: inline `{orig.strip()[:70]}` -> `{new.strip()[:70]}`")
            continue

        # Shape 4: bare-word agent tokens (table cells, prose like "<agent> agent").
        # (a) unambiguous hyphenated names -> survivor agent, or PROSE_NONE mechanism.
        def repl_bare(mobj):
            d = mobj.group(0)
            if MAP.get(d):
                return MAP[d]
            return PROSE_NONE.get(d, "(retired)")
        new = re.sub(r"(?<![\w-])(" + UNAMBIG_ALT + r")(?![\w-])", repl_bare, new)
        # (b) ambiguous bare "planner"/"project-manager"/"brainstormer" in clear agent contexts
        for amb in ("project-manager", "planner", "brainstormer"):
            repl = MAP.get(amb) or PROSE_NONE.get(amb, "(retired)")
            # "<amb> agent"
            new = re.sub(r"(?<![\w-])" + re.escape(amb) + r"(?=\s+agent\b)", repl, new)
            # table cell bounded by | <amb> |
            new = re.sub(r"(?<=\|\s)" + re.escape(amb) + r"(?=\s\|)", repl, new)
            # agent column listing:  | ... project-manager, campaign-runner |  or  "... + project-manager"
            new = re.sub(r"(?<![\w-])" + re.escape(amb) + r"(?=\s*[,+]\s)", repl, new)
            new = re.sub(r"(?<=[,+]\s)" + re.escape(amb) + r"(?![\w-])", repl, new)
        if new != orig:
            out_lines.append(new)
            changed_here.append(f"{i+1}: bareword `{orig.strip()[:60]}` -> `{new.strip()[:60]}`")
            continue

        # Anything still matching DEAD that we did not classify: leave + flag
        out_lines.append(ln)
        if re.search(DEAD_ALT, ln):
            changed_here.append(f"{i+1}: UNHANDLED (left as-is): {ln.strip()[:90]}")

    if changed_here:
        new_raw = "\n".join(out_lines)
        if "--apply" in sys.argv:
            path.write_text(new_raw, encoding="utf-8")
        rel = path.relative_to(ROOT)
        changelog.append((str(rel), changed_here))

# --- YAML pass: functional dispatch + data keys (added 260611) -----------------
# Only the named functional files; these are runtime, not prose, so they get a
# narrow, structure-aware pass instead of the line regexes above.
YAML_TARGETS = [
    ROOT / "skills/campaign-runner/templates/campaign-types/lead-gen.yaml",
    ROOT / "skills/campaign-runner/templates/campaign-types/content-seo.yaml",
    ROOT / "skills/campaign-runner/templates/campaign-types/retention.yaml",
    ROOT / "skills/campaign-runner/templates/campaign-types/product-launch.yaml",
    ROOT / "skills/common/data/mcp-mapping-matrix.yaml",
]
SCALAR_RE = re.compile(r"^(\s*)agent:\s*(" + DEAD_ALT + r")\s*$")
LIST_ITEM_RE = re.compile(r"^(\s*)-\s+(" + DEAD_ALT + r")\s*$")
MAPKEY_RE = re.compile(r"^(  )(" + DEAD_ALT + r"):\s*$")  # agent_mcp_map keys, 2-space indent

def indent_of(s):
    return len(s) - len(s.lstrip(" "))

for path in YAML_TARGETS:
    if not path.exists():
        continue
    lines = path.read_text(encoding="utf-8").split("\n")
    out_lines = []
    changed_here = []
    i = 0
    in_agent_mcp_map = False
    # Pre-seed with the LIVE (already-surviving) keys in agent_mcp_map so a dead
    # key renamed onto an existing survivor key (seo-specialist -> researcher,
    # where researcher: already exists) is dropped, not duplicated.
    seen_keys_in_map = set()
    _scan_map = False
    for _ln in lines:
        if _ln.startswith("agent_mcp_map:"):
            _scan_map = True
            continue
        if _scan_map:
            if _ln and not _ln.startswith(" ") and _ln.rstrip().endswith(":"):
                break  # next top-level key ends the block
            _mk = re.match(r"^  ([a-z0-9-]+):\s*$", _ln)
            if _mk and _mk.group(1) not in MAP:  # only live (non-dead) keys
                seen_keys_in_map.add(_mk.group(1))
    while i < len(lines):
        ln = lines[i]
        if ln.startswith("agent_mcp_map:"):
            in_agent_mcp_map = True
        elif ln and not ln.startswith(" ") and ln.rstrip().endswith(":"):
            in_agent_mcp_map = False  # left the block at next top-level key

        # Y1: scalar dispatch key
        m = SCALAR_RE.match(ln)
        if m:
            dead = m.group(2)
            repl = AGENT_SURVIVOR[dead]
            out_lines.append(f"{m.group(1)}agent: {repl}")
            changed_here.append(f"{i+1}: `agent: {dead}` -> `agent: {repl}`")
            i += 1
            continue

        # Y2a: agent_mcp_map dead KEY (rename key + its child block; dedup on collision)
        if in_agent_mcp_map:
            mk = MAPKEY_RE.match(ln)
            if mk:
                dead = mk.group(2)
                repl = AGENT_SURVIVOR[dead]
                # gather child block (deeper-indented lines)
                child = []
                j = i + 1
                while j < len(lines) and (lines[j].strip() == "" or indent_of(lines[j]) > 2):
                    child.append(lines[j]); j += 1
                if repl in seen_keys_in_map:
                    changed_here.append(f"{i+1}: dropped dead map-key `{dead}:` (survivor `{repl}` already present)")
                else:
                    out_lines.append(f"  {repl}:")
                    out_lines.extend(child)
                    seen_keys_in_map.add(repl)
                    changed_here.append(f"{i+1}: map-key `{dead}:` -> `{repl}:`")
                i = j
                continue

        # Y2b: list item under an "agents:" block — dedup the whole contiguous list
        if re.match(r"^\s*agents:\s*$", ln):
            out_lines.append(ln)
            base_ind = indent_of(ln)
            j = i + 1
            seen = []
            block_changes = []
            while j < len(lines):
                item = re.match(r"^(\s*)-\s+([a-z0-9-]+)\s*$", lines[j])
                if not item or indent_of(lines[j]) <= base_ind:
                    break
                ind, name = item.group(1), item.group(2)
                repl = AGENT_SURVIVOR.get(name, name)  # live agents pass through
                if repl not in seen:
                    seen.append(repl)
                    out_lines.append(f"{ind}- {repl}")
                if name in AGENT_SURVIVOR:
                    block_changes.append(f"{j+1}: `- {name}` -> `- {repl}`")
                elif repl != name:
                    block_changes.append(f"{j+1}: `- {name}` -> `- {repl}`")
                j += 1
            # if a survivor collapsed duplicates, note the dedup
            changed_here.extend(block_changes)
            i = j
            continue

        out_lines.append(ln)
        i += 1

    # safety net: flag any dead token we failed to classify
    for k, ol in enumerate(out_lines):
        if re.search(r"(?<![\w-])(" + DEAD_ALT + r")(?![\w-])", ol):
            changed_here.append(f"{k+1}: UNHANDLED (left as-is): {ol.strip()[:90]}")

    if changed_here:
        new_raw = "\n".join(out_lines)
        if "--apply" in sys.argv:
            path.write_text(new_raw, encoding="utf-8")
        rel = path.relative_to(ROOT)
        changelog.append((str(rel), changed_here))

# report
n_files = len(changelog)
n_edits = sum(len(c) for _, c in changelog)
n_unhandled = sum(1 for _, c in changelog for line in c if "UNHANDLED" in line)
mode = "APPLIED" if "--apply" in sys.argv else "DRY-RUN"
print(f"[{mode}] files touched: {n_files}  edits: {n_edits}  unhandled: {n_unhandled}")
if "--verbose" in sys.argv or n_unhandled:
    for rel, c in changelog:
        for line in c:
            if "UNHANDLED" in line or "--verbose" in sys.argv:
                print(f"  {rel}:{line}")
